services:
  java:
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=-Dspring.datasource.url=jdbc:mysql://database:3306/filesdb -Dspring.datasource.username=root -Dspring.datasource.password=mauFJcuf5dhRMQrjj -Dpython.baseUrl=http://python:5000

  database:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: filesDB
      MYSQL_ROOT_PASSWORD: mauFJcuf5dhRMQrjj
    ports:
      - "33061:3306"
    volumes:
      - C:\docker\dockerVol\mysql:/var/lib/mysql
      - C:\Projects\shower_singer_java\src\main\resources\scripts\:/docker-entrypoint-initdb.d/

  python:
    image: ghcr.io/kingarthur69/shower-singer-combiner:master
    ports:
      - "5000:5000"
    volumes:
      - C:\docker\dockerVol\audio\model:/app/pretrained_models