DROP DATABASE IF EXISTS filesdb;
DROP USER IF EXISTS `fileadmin`@`%`;
DROP USER IF EXISTS `fileuser`@`%`;
CREATE DATABASE IF NOT EXISTS filesdb CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS `fileadmin`@`%` IDENTIFIED WITH mysql_native_password BY 'password';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, EXECUTE, CREATE VIEW, SHOW VIEW,
    CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER ON `filesdb`.* TO `fileadmin`@`%`;
CREATE USER IF NOT EXISTS `fileuser`@`%` IDENTIFIED WITH mysql_native_password BY 'password';
GRANT SELECT, INSERT, UPDATE, DELETE, SHOW VIEW ON `filesdb`.* TO `fileuser`@`%`;
FLUSH PRIVILEGES;